### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by PierrotLaLune** [jb-1980/khan-graphql#30]
Hi Joseph,

Just wanted to thank you for your post in the khanimport repository.

I will study your khan-graphql code and hopefully be able to implement my moodle plugin to retrieve grades using it.

Would you say it would be easier to port to PHP or create a wrapper for a service ? ... I have no idea how to create a service, but I can probably find something useful on youtube :-)

Thanks a lot for your offer to help !
Pierre

**Comment by jb-1980** [comment]
With my experience, it would be easier to wrap the library in a service. This is because I never mastered PHP, and would have to learn how to store cookies from an HTTP request. But if you are a PHP master, it may be really easy to port.

A naive example of wrapping in a service would be something like this (a basic express node server):
```typescript
const express = require('express')
const {KhanApi} = require("khan-graphql")
const app = express()
const port = 3000

const KHAN_USERNAME = "district-username"
const KHAN_PASSWORD = "district-password"

app.get('/progressByStudent/:classId', async (req, res) => {
  const classId = req.params.classId
  const kapi = new KhanAPI()
  await kapi.authenticate(KHAN_USERNAME, KHAN_PASSWORD)
  return kapi.progressByStudent(classId).then(response => {
    res.json(response.data)
  })
})

// Keep adding routes as relevant

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```
Serve it up at `https://khanmicroservice.myappsurl.com`. I have always liked [pm2](https://pm2.keymetrics.io/) for serving node apps. Of course, you will still need a server to serve it from, but there are a lot of services with AWS, Google Cloud, Digital Ocean, or Heroku to make it simple to serve a node app. 

With that, in your PHP app instead of making a request to the former Khan API urls, you just make a request to `https://khanmicroservice.myappsurl.com/progressByStudent/508tskpoi055`. So you may be able to reuse a lot of the code in khanimport repo.

Of course, there are other things to consider like authentication. But I hope that gives you a start.
